// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJM7fi2rmvaPgUC_d09jLoUYXOoa5-Qt8',
    appId: '1:144753646358:web:e8ebcef5b5ab9ec12f4e37',
    messagingSenderId: '144753646358',
    projectId: 'flutterfire-51e0b',
    authDomain: 'flutterfire-51e0b.firebaseapp.com',
    storageBucket: 'flutterfire-51e0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBICnXcq0gTCY1kOjlND--0vbhYOSbNP7M',
    appId: '1:144753646358:android:11f9af5c3c47ea362f4e37',
    messagingSenderId: '144753646358',
    projectId: 'flutterfire-51e0b',
    storageBucket: 'flutterfire-51e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRrEpVtJoM1CISxJ9Pxj7D-dKWG7zldew',
    appId: '1:144753646358:ios:4ad4c0d502fbf83e2f4e37',
    messagingSenderId: '144753646358',
    projectId: 'flutterfire-51e0b',
    storageBucket: 'flutterfire-51e0b.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
